### PR TITLE
Update jenkinsci-helm-source.yml

### PR DESCRIPTION
**Pull request by dmelenteanu-quorum**

### CODE REVIEW

**Comment by dmelenteanu-quorum** [comment]
This is my comment

**Comment by dmelenteanu-quorum** [comment]
This is my comment

**Comment by dmelenteanu-quorum** [comment]
This is my comment, 
This is the build url: https://ci.quorum.us/job/test-webhook-trigger-pipeline/25/

**Comment by quorumgithubservice** [comment]
Jenkins has finished building and deploying your PR.
You can find your site at: https://1.staging.example.com
Build url: https://ci.quorum.us/job/test-webhook-trigger-pipeline/32/

**Comment by quorumgithubservice** [comment]
This is my comment, 
This is the build url: https://ci.quorum.us/job/test-webhook-trigger-pipeline/34/
You can find your site at: https://1.staging.example.com

**Comment by quorumgithubservice** [comment]
Jenkins has finished building and deploying your PR.
You can find your site at: https://1.staging.example.com
Build url: https://ci.quorum.us/job/test-webhook-trigger-pipeline/34/

**Pull request closed without merging**
